services:
  postgres:
    image: postgres:latest
    container_name: arcade-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - private-network
    ports:
      - "5432:5432"  # Expose PostgreSQL on host machine
networks:
  public-network:
    driver: bridge
  private-network:
    internal: false

volumes:
  postgres_data:

